CREATE DATABASE scm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE amon DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE rman DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE hue DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE metastore DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE sentry DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE oozie DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE USER 'scm'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON scm.* TO 'scm'@'%';
CREATE USER 'amon'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON amon.* TO 'amon'@'%';
CREATE USER 'rman'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON rman.* TO 'rman'@'%';
CREATE USER 'hue'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON hue.* TO 'hue'@'%';
CREATE USER 'metastore'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON metastore.* TO 'metastore'@'%';
CREATE USER 'sentry'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON sentry.* TO 'sentry'@'%';
CREATE USER 'oozie'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON oozie.* TO 'oozie'@'%';